import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/sidebar/";

export default function Home() {
  return (
    <div id="app">
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />

      <h1>Lets build whatsapp 2.0</h1>
    </div>
  );
}
